robot_description_planning:
  ros__parameters:
    joint_limits:
      joint_1: {has_velocity_limits: true, max_velocity: 6.28319, has_acceleration_limits: false}
      joint_2: {has_velocity_limits: true, max_velocity: 5.23599, has_acceleration_limits: false}
      joint_3: {has_velocity_limits: true, max_velocity: 6.28319, has_acceleration_limits: false}
      joint_4: {has_velocity_limits: true, max_velocity: 7.85398, has_acceleration_limits: false}
      joint_5: {has_velocity_limits: true, max_velocity: 7.85398, has_acceleration_limits: false}
      joint_6: {has_velocity_limits: true, max_velocity: 9.42478, has_acceleration_limits: false}
